### ISSUE TITLE
Spacing & punctuation of author-work citation 

### ISSUE THREAD

**Issue by tkb-github** [t18d/attested-conjectures#6]
e.g. Plu. Caes. 45.8

Note the spacing.

**Comment by tkb-github** [comment]
Comma proves to be too troublesome for CSV, so let’s stick with full points but add spacing after author and work.

**Comment by tkb-github** [comment]
@Adoria298 and please rearrange authors & works alphabetically

**Comment by tkb-github** [comment]
Leave to me the ones without an abbreviation in LSJ.

**Comment by tkb-github** [comment]
@Adoria298 I noticed you also inserted space between numbers. Note in the example Plu. Caes. 45.8, there’s no space between a dot and a number.

Could you get this fixed?

**Comment by Adoria298** [comment]
> Comma proves to be too troublesome for CSV, so let’s stick with full points but add spacing after author and work.

Commas can be put into CSV so long as the whole of that field is enclosed in quotation marks - to do the whole row, each column on that row must be enclosed individually.

**Comment by tkb-github** [comment]
> > Comma proves to be too troublesome for CSV, so let’s stick with full points but add spacing after author and work.
> 
> Commas can be put into CSV so long as the whole of that field is enclosed in quotation marks - to do the whole row, each column on that row must be enclosed individually.

Right. That’s what looked a bit laborious to me.
