### ISSUE TITLE
amsterstam-db.csv ordering

### ISSUE THREAD

**Issue by tkb-github** [t18d/attested-conjectures#8]

**Comment by tkb-github** [comment]
@Adoria298 The order of entries is a bit weird in the last few dozens, with things from other books scattered among Rev. entries.

**Comment by tkb-github** [comment]
This probably doesn’t matter if we end up incorporating them into the main CSV.

**Comment by Adoria298** [comment]
They are already in the main CSV on that branch; amsterdam-db.csv was a staging post.

**Comment by tkb-github** [comment]
> They are already in the main CSV on that branch; amsterdam-db.csv was a staging post.

Yeah that’s what I thought you were doing.
